name: C/C++ CI

defaults:
  run:
    working-directory: /root/downlods/gitRepos

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: #My Parameter
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  get_info:
      runs-on: self-hosted
      steps:
      - name: get_info
        run: hostname
      - name: get_info2 
        run: pwd
      - name: get_info3
        run: ls -l 
  build-and-test:
      runs-on: self-hosted
      steps:
      - name: Update
        run: sudo apt update
      - name: Install_libc
        run: sudo apt install -y libc6
      - name: Install_libstdc++
        run: sudo apt install -y libstdc++6
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: list 
        run: ls -l 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled executable
          path: /root/downlods/gitRepos/hello

