name: C/C++ CI

defaults:
  run:
    working-directory: /root/downlods/gitRepos

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: #My Parameter
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  get_info:
      runs-on: self-hosted
      steps:
      - name: get_info
        run: hostname
      - name: get_info2 
        run: pwd
  build-and-test:
      runs-on: self-hosted
      steps:
      - name: Update
        run: sudo apt update
      - name: Install_libc
        run: sudo apt install -y libc6
      - name: Install_libstdc++
        run: sudo apt install -y libstdc++6
      - name: configure
        run: $GITHUB_WORKSPACE/configure
      - name: make
        run: $GITHUB_WORKSPACE/make

